

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RL_3.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class MVCCHATEntities : DbContext
{
    public MVCCHATEntities()
        : base("name=MVCCHATEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<RL_C_ACCESOS> RL_C_ACCESOS { get; set; }

    public virtual DbSet<RL_C_CORPORATIVOS> RL_C_CORPORATIVOS { get; set; }

    public virtual DbSet<RL_C_PUESTOS> RL_C_PUESTOS { get; set; }

    public virtual DbSet<RL_EMPLEADO> RL_EMPLEADO { get; set; }

    public virtual DbSet<RL_EMPLEADO_ENTRADA> RL_EMPLEADO_ENTRADA { get; set; }

    public virtual DbSet<RL_EMPLEADO_SALIDA> RL_EMPLEADO_SALIDA { get; set; }

}

}

