
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RL_3.Models
{

using System;
    using System.Collections.Generic;
    
public partial class RL_C_CORPORATIVOS
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public RL_C_CORPORATIVOS()
    {

        this.RL_EMPLEADO = new HashSet<RL_EMPLEADO>();

    }


    public int ID_CORPORATIVO { get; set; }

    public string DESC_CORPORATIVO { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RL_EMPLEADO> RL_EMPLEADO { get; set; }

}

}
