//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RL_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RL_C_ACCESOS
    {
        public int ID_ACCESO { get; set; }
        public string DESC_ACCESO { get; set; }
    }
}
